pages:
  image: debian:bullseye
  before_script:
    - apt-get update && apt-get install -y doxygen
  script:
    - doxygen doc/Doxyfile
    - mv doc/html public
  artifacts:
    paths:
      - public
  only:
    - main
